# Imagen base para compilación
FROM node:16 AS build
WORKDIR /app

# Copiar los archivos de configuración y dependencias
COPY package*.json ./
RUN npm ci

# Copiar el código fuente y compilar
COPY . .
RUN npm run build

# Imagen para producción con Nginx
FROM nginx:alpine
# Aquí está el cambio: build -> dist
COPY --from=build /app/dist /usr/share/nginx/html

# Configuración para rutas de React
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]