# Imagen base para compilación
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copiar el archivo de proyecto y restaurar dependencias
COPY ["server.csproj", "./"]
RUN dotnet restore

# Copiar el resto del código y compilar
COPY . .
RUN dotnet build "server.csproj" -c Release -o /app/build

# Publicar la aplicación
FROM build AS publish
RUN dotnet publish "server.csproj" -c Release -o /app/publish

# Imagen final, más pequeña
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .

# Crear carpeta para archivos estáticos
RUN mkdir -p wwwroot/images

# Exponer puerto y definir comando de inicio
EXPOSE 80
EXPOSE 443
ENTRYPOINT ["dotnet", "server.dll"]